apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-repo-app-of-apps
  namespace: argocd
spec:
  project: system
  source:
    repoURL: 'https://github.com/my-org/my-external-repo.git'
    targetRevision: HEAD
    path: argocd-apps
    recursive: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: your-target-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true