apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
spec:
  description: My App Project
  sourceRepos:
    - https://github.com/my-org/my-repo.git
    - https://github.com/my-org/my-external-repo.git
  destinations:
    - namespace: '*'
      server: https://my-cluster-dev.my-company.com
    - namespace: '*'
      server: https://my-cluster-prod.my-company.com
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceBlacklist:
    - group: '*'
      kind: 'Event'
  # roles:
  #   - name: my-role
  #     description: My role description
  #     policies:
  #       - p, proj:my-app-project:my-role, applications, get, my-app-*, allow
  #     groups:
  #       - my-group