apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: databases
  source:
    repoURL: https://github.com/your-org/gitops-repo.git
    targetRevision: main
    path: infrastructure/databases/postgres/overlays/dev
  destination:
    server: 'https://kubernetes.default.svc' 
    namespace: databases
  syncPolicy:
    automated:
      prune: true
      selfHeal: true