apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  project: brokers
  source:
    repoURL: https://github.com/your-org/gitops-repo.git
    targetRevision: main
    path: infrastructure/databases/message-brokers/overlays/dev
  destination:
    server: 'https://kubernetes.default.svc' # management cluster
    namespace: brokers
  syncPolicy:
    automated:
      prune: true
      selfHeal: true