apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-self
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/gitops-repo.git
    targetRevision: main
    path: infrastructure/argocd
  destination:
    server: 'https://kubernetes.default.svc' # management cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true