apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: another-app
  namespace: argocd
spec:
  project: apps
  source:
    repoURL: 'https://github.com/my-org/my-external-repo.git'
    targetRevision: main
    path: apps/another-app/overlays/dev
  destination:
    server: 'https://my-dev-cluster.my-domain.com' 
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true