apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
  namespace: argocd
spec:
  project: apps
  source:
    repoURL: https://github.com/your-org/external-gitops-repo.git
    targetRevision: main
    path: apps/flask-app/overlays/dev
  destination:
    server: 'https://kubernetes.default.svc' # same cluster
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true