apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  spec:
    project: databases
    source:
      repoURL: 'https://github.com/yourorg/infrastructure.git'
      targetRevision: HEAD
      path: infrastructure/databases/postgres/overlays/dev
    destination:
      server: 'https://kubernetes.default.svc'
      namespace: postgres
    syncPolicy:
      automated:
        prune: true
        selfHeal: true