apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  spec:
    project: brokers
    source:
      repoURL: 'https://github.com/my-org/my-repo.git'
      targetRevision: HEAD
      path: infrastructure/databases/rabbitmq/overlays/dev
    destination:
      server: 'https://kubernetes-dev.example.com'
      namespace: rabbitmq
    syncPolicy:
      automated:
        prune: true
        selfHeal: true