apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  spec:
    project: databases
    source:
      repoURL: 'https://github.com/my-org/my-repo.git'
      targetRevision: HEAD
      path: infrastructure/databases/postgres/overlays/prod
    destination:
      server: 'https://kubernetes-prod.example.com'
      namespace: postgres
    syncPolicy:
      automated:
        prune: true
        selfHeal: true