apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  spec:
    project: brokers
    source:
      repoURL: 'https://github.com/yourorg/infrastructure.git'
      targetRevision: HEAD
      path: infrastructure/databases/rabbitmq/overlays/prod
    destination:
      server: 'https://kubernetes.default.svc'
      namespace: rabbitmq
    syncPolicy:
      automated:
        prune: true
        selfHeal: true